get:
  description: "Query a Parameter resource. \nA Parameter resource is a setting that\
    \ you can apply to an Org or Entity that determines key attributes of how it is\
    \ able to use the API. \nWhen applied to an Org, the parameter affects every entity\
    \ in that Org. \nExamples of Parameters include minimum and maximum processing\
    \ totals and whether particular card types are enabled."
  parameters:
  - $ref: ../components/schemas/requestHeaderRequestTokensParams.yaml
  - $ref: ../components/schemas/requestHeaderSearchParams.yaml
  - $ref: ../components/schemas/requestHeaderTotalsParams.yaml
  - $ref: ../components/schemas/requestQueryPageNumberParams.yaml
  - $ref: ../components/schemas/requestQueryPageLimitParams.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/http200responses/parametersModel200Response.yaml
      description: Response for query on parameters resource
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error-four-hundred.yaml
      description: Error
  tags:
  - Parameters
  - Facilitator
  operationId: getParameters
post:
  description: "Create a Parameter resource. \nA Parameter resource is a setting that\
    \ you can apply to an Org or Entity that determines key attributes of how it is\
    \ able to use the API. \nWhen applied to an Org, the parameter affects every entity\
    \ in that Org. \nExamples of Parameters include minimum and maximum processing\
    \ totals and whether particular card types are enabled."
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/models/parametersPostRequestModel.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/http200responses/parametersModel200Response.yaml
      description: Response for create on parameters resource
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error-four-hundred.yaml
      description: Error
  tags:
  - Parameters
  - Facilitator
  operationId: postParameters
  parameters:
  - $ref: ../components/schemas/requestHeaderRequestTokensParams.yaml
