title: configurationsResponseResult
properties:
  response:
    title: configurationsResponseItem
    properties:
      data:
        description: The data object that the API returns for this request.
        items:
          $ref: ../models/configurationsModel.yaml
      details:
        $ref: ../details.yaml
      errors:
        $ref: ../error.yaml
