title: configurationsPutRequest
properties:
  login:
    type: string
    description: The identifier of the Login that owns this configuration resource.
  entity:
    type: string
    description: The identifier of the Entity associated with this configuration resource.
  org:
    type: string
    description: The identifier of the Org associated with this configuration resource.
  division:
    type: string
    description: The identifier of the Division associated with this configuration
      resource.
  partition:
    type: string
    description: The identifier of the Partition associated with this configuration
      resource.
  integration:
    $ref: ../enums/configurationIntegrationModel.yaml
  name:
    type: string
    description: |
      The name of this configuration resource.

      <details>
      <summary>Valid Values</summary>

      - `account` - **Account. The specified configuration will be used for bank accounts integrations.**
      - `batchTxn` - **BatchTxn. The specified configuration will be used for processing transaction batches.**
      - `binReport` - **BinReport. The specified configuration will be used for bin reports integrations.**
      - `board` - **Board. The specified configuration will be used for boarding merchants.**
      - `chargeback` - **Chargeback. The specified configuration will be used for everything related to chargebacks.**
      - `decision` - **Decision. The specified configuration will be used for everything related to decisions.**
      - `decisionBoard` - **This holds configuration for running boarding decision policy on entity through Risk MS.**
      - `decisionTxn` - **DecisionTxn is used for running transaction decision policy through the Risk MS.**
      - `echeckTxn` - **EcheckTxn. The specified configuration will be used to get reports of echeck transactions as well as getting additional information about those transactions.**
      - `encryption` - **Holds the configuration for running Google and Apple Pay encryption/decryption through the Payrix Encryption Service.**
      - `omnitoken` - **Holds the configuration parameters for omnitoken services.**
      - `onlineTxn` - **OnlineTxn. The specified configuration will be used to process transactions online without a batch.**
      - `onlineTxnSocket` - **OnlineTxnSocket.**
      - `paymentUpdates` - **PaymentUpdates.**
      - `payout` - **Payout. The specified configuration will be used for everything related to payouts.**
      - `payoutCredit` - **Holds the configuration for processing payout credit through the integration service.**
      - `payoutDebit` - **Holds the configuration for processing payouts debit through the integration service.**
      - `plaid` - **Holds the configuration parameters for Plaid services (connecting accounts, getting identity, etc.).**
      - `reports` - **Reports. The specified configuration will be used to import processed transactions.**
      - `register` - **Register.**
      - `saferPayment` - **Holds the configuration parameters for safer payment VAS.**
      - `unregister` - **Unregister.**
      - `varsheetRetrieval` - **Holds the configuration parameters for varsheet retrieval.**
      - `watchlist` - **Watchlist. The specified configuration will be used to receive a watch list by the OFAC.**

      </details>
    enum:
    - account
    - batchTxn
    - binReport
    - board
    - chargeback
    - decision
    - decisionBoard
    - decisionTxn
    - echeckTxn
    - encryption
    - omnitoken
    - onlineTxn
    - onlineTxnSocket
    - paymentUpdates
    - payout
    - payoutCredit
    - payoutDebit
    - plaid
    - reports
    - register
    - saferPayment
    - unregister
    - varsheetRetrieval
    - watchlist
    x-enum-elements:
    - name: Account
      description: The specified configuration will be used for bank accounts integrations.
    - name: BatchTxn
      description: The specified configuration will be used for processing transaction batches.
    - name: BinReport
      description: The specified configuration will be used for bin reports integrations.
    - name: Board
      description: The specified configuration will be used for boarding merchants.
    - name: Chargeback
      description: The specified configuration will be used for everything related to chargebacks.
    - name: Decision
      description: The specified configuration will be used for everything related to decisions.
    - name: DecisionBoard
      description: This holds configuration for running boarding decision policy on entity through Risk MS.
    - name: DecisionTxn
      description: DecisionTxn is used for running transaction decision policy through the Risk MS.
    - name: EcheckTxn
      description: The specified configuration will be used to get reports of echeck transactions as well as getting additional information about those transactions.
    - name: Encryption
      description: Holds the configuration for running Google and Apple Pay encryption/decryption through the Payrix Encryption Service.
    - name: Omnitoken
      description: Holds the configuration parameters for omnitoken services.
    - name: OnlineTxn
      description: The specified configuration will be used to process transactions online without a batch.
    - name: OnlineTxnSocket
      description: OnlineTxnSocket.
    - name: PaymentUpdates
      description: PaymentUpdates.
    - name: Payout
      description: The specified configuration will be used for everything related to payouts.
    - name: PayoutCredit
      description: Holds the configuration for processing payout credit through the integration service.
    - name: PayoutDebit
      description: Holds the configuration for processing payouts debit through the integration service.
    - name: Plaid
      description: Holds the configuration parameters for Plaid services (connecting accounts, getting identity, etc.).
    - name: Reports
      description: The specified configuration will be used to import processed transactions.
    - name: Register
      description: Register.
    - name: SaferPayment
      description: Holds the configuration parameters for safer payment VAS.
    - name: Unregister
      description: Unregister.
    - name: VarsheetRetrieval
      description: Holds the configuration parameters for varsheet retrieval.
    - name: Watchlist
      description: The specified configuration will be used to receive a watch list by the OFAC.
  type:
    $ref: ../enums/configurationTypeModel.yaml
  options:
    type: string
    description: The options used for this configuration integration.
  inactive:
    $ref: ../inactive.yaml
  frozen:
    $ref: ../frozen.yaml

